diff ./zielgruppe_GESO.tex ./zielgruppe_GESO.tex.new
diff ./bbwLayoutPage.tex ./bbwLayoutPage.tex.new
diff ./zielgruppe_TRAINER.tex ./zielgruppe_TRAINER.tex.new
diff ./zielgruppe_TRAINER_GESO.tex ./zielgruppe_TRAINER_GESO.tex.new
diff ./zielgruppe_TRAINER_ALLG.tex ./zielgruppe_TRAINER_ALLG.tex.new
diff ./zielgruppe_HECH.tex ./zielgruppe_HECH.tex.new
diff ./zielgruppe_ALLG.tex ./zielgruppe_ALLG.tex.new
diff ./impressum.tex ./impressum.tex.new
diff ./zielgruppe_TRAINER_RLP.tex ./zielgruppe_TRAINER_RLP.tex.new
diff ./zielgruppe_TRAINER_HECH.tex ./zielgruppe_TRAINER_HECH.tex.new
diff ./bbwLayout.tex ./bbwLayout.tex.new
diff ./zielgruppe.tex ./zielgruppe.tex.new
diff ./zielgruppe_RLP.tex ./zielgruppe_RLP.tex.new
diff ./hyphenAll.tex ./hyphenAll.tex.new
diff ./bbwLayoutSlide.tex ./bbwLayoutSlide.tex.new
diff ./inputs/bbwInput.tex ./inputs/bbwInput.tex.new
diff ./inputs/matheMakros.tex ./inputs/matheMakros.tex.new
diff ./inputs/bbwMakros.tex ./inputs/bbwMakros.tex.new
diff ./inputs/bbwUsePackages.tex ./inputs/bbwUsePackages.tex.new
diff ./inputs/bbwLayout.tex ./inputs/bbwLayout.tex.new
diff ./bbwLayoutDoc.tex ./bbwLayoutDoc.tex.new
diff ./zielgruppe_TALS.tex ./zielgruppe_TALS.tex.new
diff ./bbwLayoutPruefung.tex ./bbwLayoutPruefung.tex.new
diff ./zielgruppe_TRAINER_TALS.tex ./zielgruppe_TRAINER_TALS.tex.new
